### ISSUE TITLE
How to use it with SCSS?

### ISSUE THREAD

**Issue by dennisfrijlink** [nuxt-community/color-mode-module#79]
Currently I'm using Nuxt.js with SCSS. In my general SCSS I'm using a map function for declaring the background colors based on the classname:
```scss
$colors:(
    lightgrey: #EBEDEE
);

@each $name, $hex in $colors {
    .has-background-#{"" + $name} {
        background-color: $hex;
    }
}
```

Now I'm very interested in using Nuxt Color Mode, but I tried everything but still doesn't work. I tried to declare the variables like nuxt-color-mode showed in the tutorial:
```scss
.light-mode {
    --primary: #196b69;
    --accent: #e69496;
}
.dark-mode {
    --primary: red;
    --accent: blue;
}

$colors:(
    primary: var(--primary);
    accent: var(--accent);
);

@each $name, $hex in $colors {
    .has-background-#{"" + $name} {
        background-color: $hex;
    }
}
```

But also that didn't work. Is it possible to use nuxt-color-mode with SCSS and how?
Thanks in advance.
